/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author G
 */
public class Olejarz_Kacper_Kalkulator1 extends javax.swing.JFrame {

    /**
     * Creates new form Olejarz_Kacper_Kalkulator1
     */ 
    double num,ans;
    int calculation;
       
    public Olejarz_Kacper_Kalkulator1() {
        initComponents();
        
    /**
     *
     */
    }
    public void disable() 
    {
    ko_Text.setEnabled(false);
    
    ko_1.setEnabled(false);
    ko_2.setEnabled(false);
    ko_3.setEnabled(false);
    ko_4.setEnabled(false);
    ko_5.setEnabled(false);
    ko_6.setEnabled(false);
    ko_7.setEnabled(false);
    ko_8.setEnabled(false);
    ko_9.setEnabled(false);
    ko_0.setEnabled(false);
    ko_procent.setEnabled(false);
    ko_dzielenie.setEnabled(false);
    ko_mnozenie.setEnabled(false);
    ko_odejmowanie.setEnabled(false);
    ko_dodawanie.setEnabled(false);
    ko_rownasie.setEnabled(false);
    ko_przecinek.setEnabled(false);
    ko_przycisk.setEnabled(false);
    ko_AC.setEnabled(false);
    
    }
     public void enable() 
    {
    ko_Text.setEnabled(true);
    
    ko_1.setEnabled(true);
    ko_2.setEnabled(true);
    ko_3.setEnabled(true);
    ko_4.setEnabled(true);
    ko_5.setEnabled(true);
    ko_6.setEnabled(true);
    ko_7.setEnabled(true);
    ko_8.setEnabled(true);
    ko_9.setEnabled(true);
    ko_0.setEnabled(true);
    ko_procent.setEnabled(true);
    ko_dzielenie.setEnabled(true);
    ko_mnozenie.setEnabled(true);
    ko_odejmowanie.setEnabled(true);
    ko_dodawanie.setEnabled(true);
    ko_rownasie.setEnabled(true);
    ko_przecinek.setEnabled(true);
    ko_przycisk.setEnabled(true);
    ko_AC.setEnabled(true);
    
    }
 public void arithmetic_operation()
        {
        switch(calculation)
        {
                  case 1:
                ans= num + Double.parseDouble(ko_Text.getText());
                ko_Text.setText(Double.toString(ans));
                break;
                
                  case 2:
                ans= num - Double.parseDouble(ko_Text.getText());
                ko_Text.setText(Double.toString(ans));
                break;
                
                  case 3:
                ans= num * Double.parseDouble(ko_Text.getText());
                ko_Text.setText(Double.toString(ans));
                break;
                  case 4:
                ans= num / Double.parseDouble(ko_Text.getText());
                ko_Text.setText(Double.toString(ans));
                break;
        }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ko_ON = new javax.swing.JRadioButton();
        ko_OFF = new javax.swing.JRadioButton();
        ko_Text = new javax.swing.JTextField();
        ko_AC = new javax.swing.JButton();
        ko_przycisk = new javax.swing.JButton();
        ko_procent = new javax.swing.JButton();
        ko_dzielenie = new javax.swing.JButton();
        ko_1 = new javax.swing.JButton();
        ko_3 = new javax.swing.JButton();
        ko_2 = new javax.swing.JButton();
        ko_mnozenie = new javax.swing.JButton();
        ko_5 = new javax.swing.JButton();
        ko_6 = new javax.swing.JButton();
        ko_odejmowanie = new javax.swing.JButton();
        ko_4 = new javax.swing.JButton();
        ko_dodawanie = new javax.swing.JButton();
        ko_9 = new javax.swing.JButton();
        ko_8 = new javax.swing.JButton();
        ko_7 = new javax.swing.JButton();
        ko_0 = new javax.swing.JButton();
        ko_przecinek = new javax.swing.JButton();
        ko_rownasie = new javax.swing.JButton();
        ko_LABEL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setFocusableWindowState(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        ko_ON.setBackground(new java.awt.Color(51, 255, 0));
        buttonGroup1.add(ko_ON);
        ko_ON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ko_ON.setText("ON");
        ko_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_ONActionPerformed(evt);
            }
        });

        ko_OFF.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(ko_OFF);
        ko_OFF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ko_OFF.setText("OFF");
        ko_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_OFFActionPerformed(evt);
            }
        });

        ko_Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ko_Text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ko_AC.setBackground(new java.awt.Color(153, 153, 153));
        ko_AC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_AC.setText("AC");
        ko_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_ACActionPerformed(evt);
            }
        });

        ko_przycisk.setBackground(new java.awt.Color(153, 153, 153));
        ko_przycisk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ko_przycisk.setText("+/-");
        ko_przycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_przyciskActionPerformed(evt);
            }
        });

        ko_procent.setBackground(new java.awt.Color(153, 153, 153));
        ko_procent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_procent.setText("%");

        ko_dzielenie.setBackground(new java.awt.Color(204, 0, 0));
        ko_dzielenie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_dzielenie.setText("/");
        ko_dzielenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_dzielenieActionPerformed(evt);
            }
        });

        ko_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_1.setText("1");
        ko_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_1ActionPerformed(evt);
            }
        });

        ko_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_3.setText("3");
        ko_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_3ActionPerformed(evt);
            }
        });

        ko_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_2.setText("2");
        ko_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_2ActionPerformed(evt);
            }
        });

        ko_mnozenie.setBackground(new java.awt.Color(204, 0, 0));
        ko_mnozenie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_mnozenie.setText("x");
        ko_mnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_mnozenieActionPerformed(evt);
            }
        });

        ko_5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_5.setText("5");
        ko_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_5ActionPerformed(evt);
            }
        });

        ko_6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_6.setText("6");
        ko_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_6ActionPerformed(evt);
            }
        });

        ko_odejmowanie.setBackground(new java.awt.Color(204, 0, 0));
        ko_odejmowanie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_odejmowanie.setText("-");
        ko_odejmowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_odejmowanieActionPerformed(evt);
            }
        });

        ko_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_4.setText("4");
        ko_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_4ActionPerformed(evt);
            }
        });

        ko_dodawanie.setBackground(new java.awt.Color(204, 0, 0));
        ko_dodawanie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_dodawanie.setText("+");
        ko_dodawanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_dodawanieActionPerformed(evt);
            }
        });

        ko_9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_9.setText("9");
        ko_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_9ActionPerformed(evt);
            }
        });

        ko_8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_8.setText("8");
        ko_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_8ActionPerformed(evt);
            }
        });

        ko_7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_7.setText("7");
        ko_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_7ActionPerformed(evt);
            }
        });

        ko_0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ko_0.setText("0");
        ko_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ko_0.setHideActionText(true);
        ko_0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ko_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_0ActionPerformed(evt);
            }
        });

        ko_przecinek.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_przecinek.setText(",");
        ko_przecinek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_przecinekActionPerformed(evt);
            }
        });

        ko_rownasie.setBackground(new java.awt.Color(204, 0, 0));
        ko_rownasie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ko_rownasie.setText("=");
        ko_rownasie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_rownasieActionPerformed(evt);
            }
        });

        ko_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ko_ON)
                                .addGap(18, 18, 18)
                                .addComponent(ko_OFF)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ko_Text)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ko_0, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ko_przecinek, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ko_rownasie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ko_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ko_przycisk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ko_procent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ko_dzielenie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ko_1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ko_2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ko_3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ko_mnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ko_4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(ko_5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ko_6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ko_odejmowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ko_7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ko_8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ko_9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ko_dodawanie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ko_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ko_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ko_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ko_procent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ko_dzielenie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ko_przycisk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ko_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_mnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_odejmowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_dodawanie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ko_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ko_przecinek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ko_rownasie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_ON)
                    .addComponent(ko_OFF))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Plik");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("ZAMKNIJ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ko_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_OFFActionPerformed
       disable();
    }//GEN-LAST:event_ko_OFFActionPerformed

    private void ko_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_1ActionPerformed
        ko_Text.setText(ko_Text.getText()+ "1");
    }//GEN-LAST:event_ko_1ActionPerformed

    private void ko_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_2ActionPerformed
    ko_Text.setText(ko_Text.getText()+ "2");
    }//GEN-LAST:event_ko_2ActionPerformed

    private void ko_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_3ActionPerformed
        ko_Text.setText(ko_Text.getText()+ "3");
    }//GEN-LAST:event_ko_3ActionPerformed

    private void ko_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_4ActionPerformed
        ko_Text.setText(ko_Text.getText()+ "4");
    }//GEN-LAST:event_ko_4ActionPerformed

    private void ko_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_5ActionPerformed
        ko_Text.setText(ko_Text.getText()+ "5");
    }//GEN-LAST:event_ko_5ActionPerformed

    private void ko_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_6ActionPerformed
      ko_Text.setText(ko_Text.getText()+ "6");
    }//GEN-LAST:event_ko_6ActionPerformed

    private void ko_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_7ActionPerformed
         ko_Text.setText(ko_Text.getText()+ "7");
    }//GEN-LAST:event_ko_7ActionPerformed

    private void ko_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_8ActionPerformed
        ko_Text.setText(ko_Text.getText()+ "8");
    }//GEN-LAST:event_ko_8ActionPerformed

    private void ko_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_9ActionPerformed
       ko_Text.setText(ko_Text.getText()+ "9");
    }//GEN-LAST:event_ko_9ActionPerformed

    private void ko_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_0ActionPerformed
       ko_Text.setText(ko_Text.getText()+ "0");;
    }//GEN-LAST:event_ko_0ActionPerformed

    private void ko_dzielenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_dzielenieActionPerformed
           num = Double.parseDouble(ko_Text.getText());
         calculation =4;
         ko_Text.setText("");
         ko_LABEL.setText(num + "/");
    }//GEN-LAST:event_ko_dzielenieActionPerformed

    private void ko_mnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_mnozenieActionPerformed
          num = Double.parseDouble(ko_Text.getText());
         calculation =3;
         ko_Text.setText("");
         ko_LABEL.setText(num + "x");
    }//GEN-LAST:event_ko_mnozenieActionPerformed

    private void ko_odejmowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_odejmowanieActionPerformed
           num = Double.parseDouble(ko_Text.getText());
         calculation =2;
         ko_Text.setText("");
         ko_LABEL.setText(num + "-");
    }//GEN-LAST:event_ko_odejmowanieActionPerformed

    private void ko_dodawanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_dodawanieActionPerformed
         num = Double.parseDouble(ko_Text.getText());
         calculation =1;
         ko_Text.setText("");
         ko_LABEL.setText(num + "+");
    }//GEN-LAST:event_ko_dodawanieActionPerformed

    private void ko_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_ACActionPerformed
        ko_Text.setText("");
    }//GEN-LAST:event_ko_ACActionPerformed

    private void ko_przecinekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_przecinekActionPerformed
        ko_Text.setText(ko_Text.getText()+ ",");
    }//GEN-LAST:event_ko_przecinekActionPerformed

    private void ko_przyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_przyciskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ko_przyciskActionPerformed

    private void ko_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_ONActionPerformed
    enable();    
    }//GEN-LAST:event_ko_ONActionPerformed

    private void ko_rownasieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_rownasieActionPerformed
        arithmetic_operation();
        ko_LABEL.setText("");
    }//GEN-LAST:event_ko_rownasieActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olejarz_Kacper_Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olejarz_Kacper_Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olejarz_Kacper_Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olejarz_Kacper_Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olejarz_Kacper_Kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ko_0;
    private javax.swing.JButton ko_1;
    private javax.swing.JButton ko_2;
    private javax.swing.JButton ko_3;
    private javax.swing.JButton ko_4;
    private javax.swing.JButton ko_5;
    private javax.swing.JButton ko_6;
    private javax.swing.JButton ko_7;
    private javax.swing.JButton ko_8;
    private javax.swing.JButton ko_9;
    private javax.swing.JButton ko_AC;
    private javax.swing.JLabel ko_LABEL;
    private javax.swing.JRadioButton ko_OFF;
    private javax.swing.JRadioButton ko_ON;
    private javax.swing.JTextField ko_Text;
    private javax.swing.JButton ko_dodawanie;
    private javax.swing.JButton ko_dzielenie;
    private javax.swing.JButton ko_mnozenie;
    private javax.swing.JButton ko_odejmowanie;
    private javax.swing.JButton ko_procent;
    private javax.swing.JButton ko_przecinek;
    private javax.swing.JButton ko_przycisk;
    private javax.swing.JButton ko_rownasie;
    // End of variables declaration//GEN-END:variables
}
